### ISSUE TITLE
Exporting to PDF throws error "The document is not open."

### ISSUE THREAD

**Issue by donaldthai** [ignatandrei/Export_Word_Excel_PDF_CSV_HTML#2]
When calling ExportTo method to convert list to pdf, the method throws an error that says "The document is not open.".

I'm not too sure why it's happening. Any ideas?

Here's the Stacktrack:
at iTextSharp.text.pdf.PdfWriter.get_DirectContent()
   at iTextSharp.text.pdf.PdfDocument.NewPage()
   at iTextSharp.text.pdf.PdfDocument.Close()
   at iTextSharp.text.Document.Close()
   at ExporterObjects.ExportBase.CreateFilePDF(String ItextSharpXML, String FileName) in #apc:line 493
   at ExporterObjects.ExportBase.ExportTo(IEnumerable col, Type type, ExportToFormat exp, String FileName) in #apc:line 564
   at ExporterObjects.ExportList`1.ExportTo(IEnumerable`1 col, ExportToFormat exp, String FileName) in #bpc:line 23

**Comment by donaldthai** [comment]
Nvm, I was dynamically creating the cshtml partial files and had a typo in it. Once I fixed that, everything worked.
